# linter示例:https://github.com/marmotedu/iam/blob/master/.golangci.yaml
# 如果有diff提示报错, brew install diffutils
# options for analysis running
run:
  timeout: 10m
  issues-exit-code: 1
  tests: false

#output:
#  path-prefix: "xxxxx"

linters:
  disable-all: true
  enable:
    - typecheck
    - asciicheck
    - bodyclose
#    - cyclop
#    - deadcode
#    - depguard
    - dogsled
#    - dupl
    - durationcheck
#    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
#    - forbidigo
#    - funlen
#    - gci
#    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
#    - godot
    - godox
    - gofmt
#    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
#    - lll
    - makezero
    - misspell
    - nakedret
#    - nestif
    - nilerr
#    - nlreturn
    - noctx
    - nolintlint
#    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
#    - unused
    - whitespace
    - bidichk
    - revive
    - execinquery
    - nosprintfhostport
    - grouper
    - decorder
    - errchkjson
#    - maintidx
#    - containedctx
#    - tagliatelle
#    - nonamedreturns
    - nilnil
    - tenv
#    - varnamelen
    - contextcheck
    - errname
  fast: false

linters-settings:
#  lll:
#    line-length: 200
  exhaustive:
    default-signifies-exhaustive: true
#  funlen:
#    lines: 150
#    statements: 50
  gocognit:
    min-complexity: 110
  gocyclo:
    min-complexity: 40
#  nestif:
#    min-complexity: 6
  godox:
    keywords:
      - GODOXFORBID
  gosec:
    excludes:
      - G501
      - G401
  nakedret:
    max-func-lines: 50
  revive:
    rules:
      - name: var-naming
        disabled: true
  staticcheck:
    checks: ["all", "-SA1012"]   #禁用nil context的检查
  stylecheck:
    checks:
      ["all", "-ST1003"]  #forbid name-check for variables and packages